// This file is auto-generated by tools/embed_assets.py
// DO NOT EDIT MANUALLY

/// Returns `(gzipped_bytes, content_type)` for a given request path,
/// or `None` if the asset does not exist.
///
/// "/" is automatically mapped to "/index.html".
pub fn get_asset(path: &str) -> Option<(&'static [u8], &'static str)> {
    // Normalise the path: strip leading '/', map empty → index.html
    let normalised = match path.trim_start_matches('/') {
        "" => "index.html",
        p => p,
    };

    match normalised {
        "_app/env.js" => Some((_APP_ENV_JS, "application/javascript")),
        "_app/immutable/assets/0.BTm9rfIj.css" => {
            Some((_APP_IMMUTABLE_ASSETS_0_BTM9RFIJ_CSS, "text/css"))
        }
        "_app/immutable/assets/10.CHCeSEGk.css" => {
            Some((_APP_IMMUTABLE_ASSETS_10_CHCESEGK_CSS, "text/css"))
        }
        "_app/immutable/assets/11.CtZRhhKy.css" => {
            Some((_APP_IMMUTABLE_ASSETS_11_CTZRHHKY_CSS, "text/css"))
        }
        "_app/immutable/assets/2.VT7GzHJ_.css" => {
            Some((_APP_IMMUTABLE_ASSETS_2_VT7GZHJ__CSS, "text/css"))
        }
        "_app/immutable/assets/3.BDQ5X82w.css" => {
            Some((_APP_IMMUTABLE_ASSETS_3_BDQ5X82W_CSS, "text/css"))
        }
        "_app/immutable/assets/4.DfmANkGp.css" => {
            Some((_APP_IMMUTABLE_ASSETS_4_DFMANKGP_CSS, "text/css"))
        }
        "_app/immutable/assets/5.ACHpewCG.css" => {
            Some((_APP_IMMUTABLE_ASSETS_5_ACHPEWCG_CSS, "text/css"))
        }
        "_app/immutable/assets/6.BZ1eihYE.css" => {
            Some((_APP_IMMUTABLE_ASSETS_6_BZ1EIHYE_CSS, "text/css"))
        }
        "_app/immutable/assets/7.C1N9sdEq.css" => {
            Some((_APP_IMMUTABLE_ASSETS_7_C1N9SDEQ_CSS, "text/css"))
        }
        "_app/immutable/assets/8.D6IfTvsi.css" => {
            Some((_APP_IMMUTABLE_ASSETS_8_D6IFTVSI_CSS, "text/css"))
        }
        "_app/immutable/assets/9.pUm_PKGT.css" => {
            Some((_APP_IMMUTABLE_ASSETS_9_PUM_PKGT_CSS, "text/css"))
        }
        "_app/immutable/assets/DeviceSidebar.BOA5LnCM.css" => {
            Some((_APP_IMMUTABLE_ASSETS_DEVICESIDEBAR_BOA5LNCM_CSS, "text/css"))
        }
        "_app/immutable/chunks/3acnsFrT.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_3ACNSFRT_JS, "application/javascript"))
        }
        "_app/immutable/chunks/B5xf_oRu.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_B5XF_ORU_JS, "application/javascript"))
        }
        "_app/immutable/chunks/B9cBbv2E.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_B9CBBV2E_JS, "application/javascript"))
        }
        "_app/immutable/chunks/BGesMc_X.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_BGESMC_X_JS, "application/javascript"))
        }
        "_app/immutable/chunks/BLTvsoaZ.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_BLTVSOAZ_JS, "application/javascript"))
        }
        "_app/immutable/chunks/BR4gNsfd.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_BR4GNSFD_JS, "application/javascript"))
        }
        "_app/immutable/chunks/Bhx9EHw4.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_BHX9EHW4_JS, "application/javascript"))
        }
        "_app/immutable/chunks/Bq6RWp7w.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_BQ6RWP7W_JS, "application/javascript"))
        }
        "_app/immutable/chunks/C4fKE_4a.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_C4FKE_4A_JS, "application/javascript"))
        }
        "_app/immutable/chunks/C71HuKAt.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_C71HUKAT_JS, "application/javascript"))
        }
        "_app/immutable/chunks/CVKhMu0o.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_CVKHMU0O_JS, "application/javascript"))
        }
        "_app/immutable/chunks/Cl2hF-2Z.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_CL2HF_2Z_JS, "application/javascript"))
        }
        "_app/immutable/chunks/DINAOACm.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_DINAOACM_JS, "application/javascript"))
        }
        "_app/immutable/chunks/Db4PR3F_.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_DB4PR3F__JS, "application/javascript"))
        }
        "_app/immutable/chunks/DbjJ7nwO.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_DBJJ7NWO_JS, "application/javascript"))
        }
        "_app/immutable/chunks/Dbos3XuT.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_DBOS3XUT_JS, "application/javascript"))
        }
        "_app/immutable/chunks/fy2BZYY_.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_FY2BZYY__JS, "application/javascript"))
        }
        "_app/immutable/chunks/g8d1vrjc.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_G8D1VRJC_JS, "application/javascript"))
        }
        "_app/immutable/entry/app.1eoWiKfD.js" => Some((
            _APP_IMMUTABLE_ENTRY_APP_1EOWIKFD_JS,
            "application/javascript",
        )),
        "_app/immutable/entry/start.ObWdMfQE.js" => Some((
            _APP_IMMUTABLE_ENTRY_START_OBWDMFQE_JS,
            "application/javascript",
        )),
        "_app/immutable/nodes/0.Df1VIMNm.js" => {
            Some((_APP_IMMUTABLE_NODES_0_DF1VIMNM_JS, "application/javascript"))
        }
        "_app/immutable/nodes/1.z8RZg-Ax.js" => {
            Some((_APP_IMMUTABLE_NODES_1_Z8RZG_AX_JS, "application/javascript"))
        }
        "_app/immutable/nodes/10.wnaNgfvb.js" => Some((
            _APP_IMMUTABLE_NODES_10_WNANGFVB_JS,
            "application/javascript",
        )),
        "_app/immutable/nodes/11.DfxoWv2K.js" => Some((
            _APP_IMMUTABLE_NODES_11_DFXOWV2K_JS,
            "application/javascript",
        )),
        "_app/immutable/nodes/2.CqNxa23Z.js" => {
            Some((_APP_IMMUTABLE_NODES_2_CQNXA23Z_JS, "application/javascript"))
        }
        "_app/immutable/nodes/3.BUDt0VRe.js" => {
            Some((_APP_IMMUTABLE_NODES_3_BUDT0VRE_JS, "application/javascript"))
        }
        "_app/immutable/nodes/4.BqJPc3uL.js" => {
            Some((_APP_IMMUTABLE_NODES_4_BQJPC3UL_JS, "application/javascript"))
        }
        "_app/immutable/nodes/5.BgaMCWLq.js" => {
            Some((_APP_IMMUTABLE_NODES_5_BGAMCWLQ_JS, "application/javascript"))
        }
        "_app/immutable/nodes/6.DqNWGwzS.js" => {
            Some((_APP_IMMUTABLE_NODES_6_DQNWGWZS_JS, "application/javascript"))
        }
        "_app/immutable/nodes/7.BO5QUzLK.js" => {
            Some((_APP_IMMUTABLE_NODES_7_BO5QUZLK_JS, "application/javascript"))
        }
        "_app/immutable/nodes/8.DMyblyFK.js" => {
            Some((_APP_IMMUTABLE_NODES_8_DMYBLYFK_JS, "application/javascript"))
        }
        "_app/immutable/nodes/9.BmwWN5nO.js" => {
            Some((_APP_IMMUTABLE_NODES_9_BMWWN5NO_JS, "application/javascript"))
        }
        "_app/version.json" => Some((_APP_VERSION_JSON, "application/json")),
        "index.html" => Some((INDEX_HTML, "text/html; charset=utf-8")),
        "robots.txt" => Some((ROBOTS_TXT, "text/plain")),
        _ => None,
    }
}

static _APP_ENV_JS: &[u8] = include_bytes!("../../assets/_app/env.js.gz");
static _APP_IMMUTABLE_ASSETS_0_BTM9RFIJ_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/0.BTm9rfIj.css.gz");
static _APP_IMMUTABLE_ASSETS_10_CHCESEGK_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/10.CHCeSEGk.css.gz");
static _APP_IMMUTABLE_ASSETS_11_CTZRHHKY_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/11.CtZRhhKy.css.gz");
static _APP_IMMUTABLE_ASSETS_2_VT7GZHJ__CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/2.VT7GzHJ_.css.gz");
static _APP_IMMUTABLE_ASSETS_3_BDQ5X82W_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/3.BDQ5X82w.css.gz");
static _APP_IMMUTABLE_ASSETS_4_DFMANKGP_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/4.DfmANkGp.css.gz");
static _APP_IMMUTABLE_ASSETS_5_ACHPEWCG_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/5.ACHpewCG.css.gz");
static _APP_IMMUTABLE_ASSETS_6_BZ1EIHYE_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/6.BZ1eihYE.css.gz");
static _APP_IMMUTABLE_ASSETS_7_C1N9SDEQ_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/7.C1N9sdEq.css.gz");
static _APP_IMMUTABLE_ASSETS_8_D6IFTVSI_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/8.D6IfTvsi.css.gz");
static _APP_IMMUTABLE_ASSETS_9_PUM_PKGT_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/9.pUm_PKGT.css.gz");
static _APP_IMMUTABLE_ASSETS_DEVICESIDEBAR_BOA5LNCM_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/DeviceSidebar.BOA5LnCM.css.gz");
static _APP_IMMUTABLE_CHUNKS_3ACNSFRT_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/3acnsFrT.js.gz");
static _APP_IMMUTABLE_CHUNKS_B5XF_ORU_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/B5xf_oRu.js.gz");
static _APP_IMMUTABLE_CHUNKS_B9CBBV2E_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/B9cBbv2E.js.gz");
static _APP_IMMUTABLE_CHUNKS_BGESMC_X_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/BGesMc_X.js.gz");
static _APP_IMMUTABLE_CHUNKS_BLTVSOAZ_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/BLTvsoaZ.js.gz");
static _APP_IMMUTABLE_CHUNKS_BR4GNSFD_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/BR4gNsfd.js.gz");
static _APP_IMMUTABLE_CHUNKS_BHX9EHW4_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/Bhx9EHw4.js.gz");
static _APP_IMMUTABLE_CHUNKS_BQ6RWP7W_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/Bq6RWp7w.js.gz");
static _APP_IMMUTABLE_CHUNKS_C4FKE_4A_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/C4fKE_4a.js.gz");
static _APP_IMMUTABLE_CHUNKS_C71HUKAT_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/C71HuKAt.js.gz");
static _APP_IMMUTABLE_CHUNKS_CVKHMU0O_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/CVKhMu0o.js.gz");
static _APP_IMMUTABLE_CHUNKS_CL2HF_2Z_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/Cl2hF-2Z.js.gz");
static _APP_IMMUTABLE_CHUNKS_DINAOACM_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/DINAOACm.js.gz");
static _APP_IMMUTABLE_CHUNKS_DB4PR3F__JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/Db4PR3F_.js.gz");
static _APP_IMMUTABLE_CHUNKS_DBJJ7NWO_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/DbjJ7nwO.js.gz");
static _APP_IMMUTABLE_CHUNKS_DBOS3XUT_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/Dbos3XuT.js.gz");
static _APP_IMMUTABLE_CHUNKS_FY2BZYY__JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/fy2BZYY_.js.gz");
static _APP_IMMUTABLE_CHUNKS_G8D1VRJC_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/g8d1vrjc.js.gz");
static _APP_IMMUTABLE_ENTRY_APP_1EOWIKFD_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/entry/app.1eoWiKfD.js.gz");
static _APP_IMMUTABLE_ENTRY_START_OBWDMFQE_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/entry/start.ObWdMfQE.js.gz");
static _APP_IMMUTABLE_NODES_0_DF1VIMNM_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/0.Df1VIMNm.js.gz");
static _APP_IMMUTABLE_NODES_1_Z8RZG_AX_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/1.z8RZg-Ax.js.gz");
static _APP_IMMUTABLE_NODES_10_WNANGFVB_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/10.wnaNgfvb.js.gz");
static _APP_IMMUTABLE_NODES_11_DFXOWV2K_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/11.DfxoWv2K.js.gz");
static _APP_IMMUTABLE_NODES_2_CQNXA23Z_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/2.CqNxa23Z.js.gz");
static _APP_IMMUTABLE_NODES_3_BUDT0VRE_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/3.BUDt0VRe.js.gz");
static _APP_IMMUTABLE_NODES_4_BQJPC3UL_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/4.BqJPc3uL.js.gz");
static _APP_IMMUTABLE_NODES_5_BGAMCWLQ_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/5.BgaMCWLq.js.gz");
static _APP_IMMUTABLE_NODES_6_DQNWGWZS_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/6.DqNWGwzS.js.gz");
static _APP_IMMUTABLE_NODES_7_BO5QUZLK_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/7.BO5QUzLK.js.gz");
static _APP_IMMUTABLE_NODES_8_DMYBLYFK_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/8.DMyblyFK.js.gz");
static _APP_IMMUTABLE_NODES_9_BMWWN5NO_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/9.BmwWN5nO.js.gz");
static _APP_VERSION_JSON: &[u8] = include_bytes!("../../assets/_app/version.json.gz");
static INDEX_HTML: &[u8] = include_bytes!("../../assets/index.html.gz");
static ROBOTS_TXT: &[u8] = include_bytes!("../../assets/robots.txt.gz");
