// This file is auto-generated by tools/embed_assets.py
// DO NOT EDIT MANUALLY

/// Returns `(gzipped_bytes, content_type)` for a given request path,
/// or `None` if the asset does not exist.
///
/// "/" is automatically mapped to "/index.html".
pub fn get_asset(path: &str) -> Option<(&'static [u8], &'static str)> {
    // Normalise the path: strip leading '/', map empty → index.html
    let normalised = match path.trim_start_matches('/') {
        "" => "index.html",
        p => p,
    };

    match normalised {
        "_app/env.js" => Some((_APP_ENV_JS, "application/javascript")),
        "_app/immutable/assets/0.Ck_kQSnr.css" => {
            Some((_APP_IMMUTABLE_ASSETS_0_CK_KQSNR_CSS, "text/css"))
        }
        "_app/immutable/assets/2.BKgONrwE.css" => {
            Some((_APP_IMMUTABLE_ASSETS_2_BKGONRWE_CSS, "text/css"))
        }
        "_app/immutable/assets/3.CRexE63P.css" => {
            Some((_APP_IMMUTABLE_ASSETS_3_CREXE63P_CSS, "text/css"))
        }
        "_app/immutable/assets/4.BI62mvoj.css" => {
            Some((_APP_IMMUTABLE_ASSETS_4_BI62MVOJ_CSS, "text/css"))
        }
        "_app/immutable/assets/5.BXboFRyl.css" => {
            Some((_APP_IMMUTABLE_ASSETS_5_BXBOFRYL_CSS, "text/css"))
        }
        "_app/immutable/chunks/1TXSdocF.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_1TXSDOCF_JS, "application/javascript"))
        }
        "_app/immutable/chunks/8tVm5QQd.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_8TVM5QQD_JS, "application/javascript"))
        }
        "_app/immutable/chunks/BBQbmmph.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_BBQBMMPH_JS, "application/javascript"))
        }
        "_app/immutable/chunks/BK9O47Hg.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_BK9O47HG_JS, "application/javascript"))
        }
        "_app/immutable/chunks/BiXtBRac.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_BIXTBRAC_JS, "application/javascript"))
        }
        "_app/immutable/chunks/C9H120tA.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_C9H120TA_JS, "application/javascript"))
        }
        "_app/immutable/chunks/CWXSZpdK.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_CWXSZPDK_JS, "application/javascript"))
        }
        "_app/immutable/chunks/CYof19dq.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_CYOF19DQ_JS, "application/javascript"))
        }
        "_app/immutable/chunks/Dw59mpKt.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_DW59MPKT_JS, "application/javascript"))
        }
        "_app/immutable/chunks/NCA8OqZL.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_NCA8OQZL_JS, "application/javascript"))
        }
        "_app/immutable/chunks/ls181ff_.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_LS181FF__JS, "application/javascript"))
        }
        "_app/immutable/chunks/vljJw44L.js" => {
            Some((_APP_IMMUTABLE_CHUNKS_VLJJW44L_JS, "application/javascript"))
        }
        "_app/immutable/entry/app.B4jmNiqt.js" => Some((
            _APP_IMMUTABLE_ENTRY_APP_B4JMNIQT_JS,
            "application/javascript",
        )),
        "_app/immutable/entry/start.NW93oQnG.js" => Some((
            _APP_IMMUTABLE_ENTRY_START_NW93OQNG_JS,
            "application/javascript",
        )),
        "_app/immutable/nodes/0.BHPazkYk.js" => {
            Some((_APP_IMMUTABLE_NODES_0_BHPAZKYK_JS, "application/javascript"))
        }
        "_app/immutable/nodes/1.CCeFGP4l.js" => {
            Some((_APP_IMMUTABLE_NODES_1_CCEFGP4L_JS, "application/javascript"))
        }
        "_app/immutable/nodes/2.B0I5EjyI.js" => {
            Some((_APP_IMMUTABLE_NODES_2_B0I5EJYI_JS, "application/javascript"))
        }
        "_app/immutable/nodes/3.BHwPMNrS.js" => {
            Some((_APP_IMMUTABLE_NODES_3_BHWPMNRS_JS, "application/javascript"))
        }
        "_app/immutable/nodes/4.CoB5sJHH.js" => {
            Some((_APP_IMMUTABLE_NODES_4_COB5SJHH_JS, "application/javascript"))
        }
        "_app/immutable/nodes/5.8OAMvb11.js" => {
            Some((_APP_IMMUTABLE_NODES_5_8OAMVB11_JS, "application/javascript"))
        }
        "_app/version.json" => Some((_APP_VERSION_JSON, "application/json")),
        "index.html" => Some((INDEX_HTML, "text/html; charset=utf-8")),
        "robots.txt" => Some((ROBOTS_TXT, "text/plain")),
        _ => None,
    }
}

static _APP_ENV_JS: &[u8] = include_bytes!("../../assets/_app/env.js.gz");
static _APP_IMMUTABLE_ASSETS_0_CK_KQSNR_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/0.Ck_kQSnr.css.gz");
static _APP_IMMUTABLE_ASSETS_2_BKGONRWE_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/2.BKgONrwE.css.gz");
static _APP_IMMUTABLE_ASSETS_3_CREXE63P_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/3.CRexE63P.css.gz");
static _APP_IMMUTABLE_ASSETS_4_BI62MVOJ_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/4.BI62mvoj.css.gz");
static _APP_IMMUTABLE_ASSETS_5_BXBOFRYL_CSS: &[u8] =
    include_bytes!("../../assets/_app/immutable/assets/5.BXboFRyl.css.gz");
static _APP_IMMUTABLE_CHUNKS_1TXSDOCF_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/1TXSdocF.js.gz");
static _APP_IMMUTABLE_CHUNKS_8TVM5QQD_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/8tVm5QQd.js.gz");
static _APP_IMMUTABLE_CHUNKS_BBQBMMPH_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/BBQbmmph.js.gz");
static _APP_IMMUTABLE_CHUNKS_BK9O47HG_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/BK9O47Hg.js.gz");
static _APP_IMMUTABLE_CHUNKS_BIXTBRAC_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/BiXtBRac.js.gz");
static _APP_IMMUTABLE_CHUNKS_C9H120TA_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/C9H120tA.js.gz");
static _APP_IMMUTABLE_CHUNKS_CWXSZPDK_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/CWXSZpdK.js.gz");
static _APP_IMMUTABLE_CHUNKS_CYOF19DQ_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/CYof19dq.js.gz");
static _APP_IMMUTABLE_CHUNKS_DW59MPKT_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/Dw59mpKt.js.gz");
static _APP_IMMUTABLE_CHUNKS_NCA8OQZL_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/NCA8OqZL.js.gz");
static _APP_IMMUTABLE_CHUNKS_LS181FF__JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/ls181ff_.js.gz");
static _APP_IMMUTABLE_CHUNKS_VLJJW44L_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/chunks/vljJw44L.js.gz");
static _APP_IMMUTABLE_ENTRY_APP_B4JMNIQT_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/entry/app.B4jmNiqt.js.gz");
static _APP_IMMUTABLE_ENTRY_START_NW93OQNG_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/entry/start.NW93oQnG.js.gz");
static _APP_IMMUTABLE_NODES_0_BHPAZKYK_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/0.BHPazkYk.js.gz");
static _APP_IMMUTABLE_NODES_1_CCEFGP4L_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/1.CCeFGP4l.js.gz");
static _APP_IMMUTABLE_NODES_2_B0I5EJYI_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/2.B0I5EjyI.js.gz");
static _APP_IMMUTABLE_NODES_3_BHWPMNRS_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/3.BHwPMNrS.js.gz");
static _APP_IMMUTABLE_NODES_4_COB5SJHH_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/4.CoB5sJHH.js.gz");
static _APP_IMMUTABLE_NODES_5_8OAMVB11_JS: &[u8] =
    include_bytes!("../../assets/_app/immutable/nodes/5.8OAMvb11.js.gz");
static _APP_VERSION_JSON: &[u8] = include_bytes!("../../assets/_app/version.json.gz");
static INDEX_HTML: &[u8] = include_bytes!("../../assets/index.html.gz");
static ROBOTS_TXT: &[u8] = include_bytes!("../../assets/robots.txt.gz");
