#!/usr/bin/env python3
"""
embed_assets.py - Compress SvelteKit build output for embedding in firmware.

Reads frontend/build/, gzips each file into assets/, then generates
firmware/src/web_assets.rs with include_bytes! macros and a get_asset() lookup.
"""

import gzip
import os
import sys
from pathlib import Path

# Resolve paths relative to this script's parent (project root)
SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
INPUT_DIR = ROOT / "frontend" / "build"
OUTPUT_DIR = ROOT / "assets"
RUST_OUT = ROOT / "firmware" / "src" / "web_assets.rs"

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".js":   "application/javascript",
    ".css":  "text/css",
    ".json": "application/json",
    ".svg":  "image/svg+xml",
    ".png":  "image/png",
    ".ico":  "image/x-icon",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".txt":  "text/plain",
    ".webmanifest": "application/manifest+json",
}

DEFAULT_CONTENT_TYPE = "application/octet-stream"


def content_type_for(path: Path) -> str:
    return CONTENT_TYPES.get(path.suffix.lower(), DEFAULT_CONTENT_TYPE)


def rust_const_name(rel_path: Path) -> str:
    """Convert a relative path to a valid Rust const identifier."""
    name = str(rel_path).replace("/", "_").replace("\\", "_").replace(".", "_").replace("-", "_")
    # Ensure it starts with a letter
    if name and name[0].isdigit():
        name = "asset_" + name
    return name.upper()


def collect_files(input_dir: Path) -> list[Path]:
    files = []
    for path in sorted(input_dir.rglob("*")):
        if path.is_file():
            files.append(path)
    return files


def gzip_file(src: Path, dst: Path, compression: int = 9) -> tuple[int, int]:
    """Compress src into dst. Returns (original_size, compressed_size)."""
    dst.parent.mkdir(parents=True, exist_ok=True)
    data = src.read_bytes()
    with gzip.open(dst, "wb", compresslevel=compression) as f:
        f.write(data)
    return len(data), dst.stat().st_size


def generate_rust(entries: list[dict]) -> str:
    """Generate the web_assets.rs Rust source file content."""
    lines = []
    lines.append("// This file is auto-generated by tools/embed_assets.py")
    lines.append("// DO NOT EDIT MANUALLY")
    lines.append("")
    lines.append("/// Returns `(gzipped_bytes, content_type)` for a given request path,")
    lines.append("/// or `None` if the asset does not exist.")
    lines.append("///")
    lines.append('/// "/" is automatically mapped to "/index.html".')
    lines.append("pub fn get_asset(path: &str) -> Option<(&'static [u8], &'static str)> {")
    lines.append("    // Normalise the path: strip leading '/', map empty → index.html")
    lines.append("    let normalised = match path.trim_start_matches('/') {")
    lines.append('        "" => "index.html",')
    lines.append("        p  => p,")
    lines.append("    };")
    lines.append("")
    lines.append("    match normalised {")

    for entry in entries:
        rel_posix = entry["rel_posix"]
        const_name = entry["const_name"]
        ct = entry["content_type"]
        lines.append(f'        "{rel_posix}" => Some(({const_name}, "{ct}")),')

    lines.append("        _ => None,")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # Emit the include_bytes! statics
    for entry in entries:
        const_name = entry["const_name"]
        asset_path_from_src = entry["asset_path_from_firmware_src"]
        lines.append(
            f'static {const_name}: &[u8] = include_bytes!("{asset_path_from_src}");'
        )

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if not INPUT_DIR.exists():
        print(f"ERROR: Input directory not found: {INPUT_DIR}", file=sys.stderr)
        print("Run 'cd frontend && bun install && bun run build' first.", file=sys.stderr)
        sys.exit(1)

    files = collect_files(INPUT_DIR)
    if not files:
        print(f"WARNING: No files found in {INPUT_DIR}")
        sys.exit(0)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    total_original = 0
    total_compressed = 0
    entries = []

    print(f"Embedding {len(files)} files from {INPUT_DIR.relative_to(ROOT)}/")
    print()

    for src in files:
        rel = src.relative_to(INPUT_DIR)
        # Use forward slashes for all keys regardless of OS
        rel_posix = rel.as_posix()
        gz_rel = Path(rel_posix + ".gz")
        dst = OUTPUT_DIR / gz_rel

        orig_size, gz_size = gzip_file(src, dst)
        total_original += orig_size
        total_compressed += gz_size

        ct = content_type_for(src)
        const_name = rust_const_name(rel)

        # Path to the .gz file as seen from firmware/src/web_assets.rs
        # i.e. relative from firmware/src/ to the assets/ dir
        asset_path_from_firmware_src = (
            Path("../..") / gz_rel.parent / gz_rel.name
        ).as_posix()
        # Normalise to use forward slashes and start from project root reference
        # actual path: <root>/assets/<rel>.gz
        # from:        <root>/firmware/src/web_assets.rs
        # relative:    ../../assets/<rel>.gz
        asset_path_from_firmware_src = (
            "../../assets/" + rel_posix + ".gz"
        )

        entries.append(
            {
                "rel_posix": rel_posix,
                "const_name": const_name,
                "content_type": ct,
                "asset_path_from_firmware_src": asset_path_from_firmware_src,
                "dst": dst,
                "orig_size": orig_size,
                "gz_size": gz_size,
            }
        )

        pct = (1 - gz_size / orig_size) * 100 if orig_size else 0
        print(f"  {rel_posix:<55} {orig_size:>8,} → {gz_size:>8,} bytes  ({pct:4.1f}% saved)")

    # Write Rust source
    RUST_OUT.parent.mkdir(parents=True, exist_ok=True)
    rust_src = generate_rust(entries)
    RUST_OUT.write_text(rust_src, encoding="utf-8")

    savings = (1 - total_compressed / total_original) * 100 if total_original else 0
    print()
    print(f"Summary:")
    print(f"  Files processed : {len(files)}")
    print(f"  Original size   : {total_original:>10,} bytes ({total_original / 1024:.1f} KB)")
    print(f"  Gzipped size    : {total_compressed:>10,} bytes ({total_compressed / 1024:.1f} KB)")
    print(f"  Savings         : {savings:.1f}%")
    print(f"  Output dir      : {OUTPUT_DIR.relative_to(ROOT)}/")
    print(f"  Rust source     : {RUST_OUT.relative_to(ROOT)}")

    # Flash budget check: 400 KB gzip limit
    budget_kb = 400
    if total_compressed > budget_kb * 1024:
        print()
        print(
            f"WARNING: gzipped assets ({total_compressed / 1024:.1f} KB) exceed "
            f"{budget_kb} KB flash budget!",
            file=sys.stderr,
        )
        sys.exit(2)


if __name__ == "__main__":
    main()
